server:
  port: 8095
  servlet:
    context-path: /random_extract

#jdbc
spring:
  datasource:
    username: hzgps_taxi
    password: hzgps_taxi
    url: jdbc:mysql://220.189.215.98:12206/hz_taxi?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Hikari will use the above plus the following to setup connection pooling
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 from dual

pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.twkf.dao: DEBUG

spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8

